### ISSUE TITLE
Exception when using a package without any components defined

### ISSUE THREAD

**Issue by mmannel** [SolidLeon/GenericLauncher#2]
[13:19:04 DEBUG]:    No components specified by this package!
[13:19:04 DEBUG]:  Read component bean from 'C:...\bootstrap.jar'
[13:19:04 DEBUG]:  Exit due to exception, see: 'C:...\ERROR_b7183c99-de13-4da8-ac83-c86ca7be105f.txt'
java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(Unknown Source)
    at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
    at sun.nio.cs.StreamDecoder.read(Unknown Source)
    at java.io.InputStreamReader.read(Unknown Source)
    at java.io.BufferedReader.fill(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.io.BufferedReader.readLine(Unknown Source)
    at java.nio.file.Files.readAllLines(Unknown Source)
    at java.nio.file.Files.readAllLines(Unknown Source)
    at launcher.controller.ComponentController.readComponentBean(ComponentController.java:110)
    at launcher.controller.ComponentController.readComponentBeans(ComponentController.java:50)
    at launcher.controller.ComponentController.run(ComponentController.java:40)
    at launcher.Launcher.run(Launcher.java:46)
    at java.lang.Thread.run(Unknown Source)

**Comment by mmannel** [comment]
Fixed, see commit 6d9964be160dcbb1681bcede675674564d8d0e3d
